export const PLATFORM_FEE_PERCENT = 15;

export const CATEGORIES = [
  { id: "1", name: "Customer Support Agents", slug: "customer-support", icon: "headset" },
  { id: "2", name: "Sales & Lead Gen Agents", slug: "sales-lead-gen", icon: "trending-up" },
  { id: "3", name: "Data Analysis Agents", slug: "data-analysis", icon: "bar-chart" },
  { id: "4", name: "Content Creation Agents", slug: "content-creation", icon: "pen-tool" },
  { id: "5", name: "Code & Dev Agents", slug: "code-dev", icon: "code" },
  { id: "6", name: "Research Agents", slug: "research", icon: "search" },
  { id: "7", name: "Workflow Automation", slug: "workflow-automation", icon: "zap" },
  { id: "8", name: "Marketing Agents", slug: "marketing", icon: "megaphone" },
  { id: "9", name: "Finance & Accounting", slug: "finance-accounting", icon: "dollar-sign" },
  { id: "10", name: "HR & Recruiting Agents", slug: "hr-recruiting", icon: "users" },
  { id: "11", name: "Legal Agents", slug: "legal", icon: "shield" },
  { id: "12", name: "Custom Agents", slug: "custom", icon: "settings" },
] as const;

export const MOCK_LISTINGS = [
  {
    id: "1",
    seller_id: "s1",
    title: "AI Customer Support Agent - 24/7 Multilingual",
    short_description: "Fully autonomous customer support agent that handles tickets, chats, and emails in 20+ languages.",
    description: "This AI agent handles your entire customer support workflow. It integrates with Zendesk, Intercom, and Freshdesk. Supports 20+ languages with native-quality responses. Includes sentiment analysis, automatic escalation, and weekly performance reports.",
    category_id: "1",
    price: 499,
    price_type: "fixed" as const,
    tags: ["customer-support", "multilingual", "zendesk", "intercom"],
    images: [],
    demo_url: "https://demo.example.com",
    status: "active" as const,
    rating: 4.8,
    review_count: 124,
    order_count: 340,
    created_at: "2025-12-01",
    seller: {
      id: "s1",
      email: "alex@example.com",
      name: "Alex Chen",
      bio: "AI engineer with 5 years building production agents. Previously at OpenAI.",
      role: "seller" as const,
      created_at: "2025-10-01",
    },
  },
  {
    id: "2",
    seller_id: "s2",
    title: "Lead Generation Agent for B2B SaaS",
    short_description: "Scrapes, qualifies, and enriches B2B leads. Integrates with your CRM automatically.",
    description: "Automated lead generation agent built for B2B SaaS companies. Scrapes prospects from LinkedIn, enriches data, scores leads based on your ICP, and pushes qualified leads directly into HubSpot or Salesforce. Includes weekly pipeline reports.",
    category_id: "2",
    price: 799,
    price_type: "fixed" as const,
    tags: ["lead-gen", "b2b", "crm", "hubspot", "salesforce"],
    images: [],
    status: "active" as const,
    rating: 4.6,
    review_count: 87,
    order_count: 215,
    created_at: "2025-11-15",
    seller: {
      id: "s2",
      email: "sarah@example.com",
      name: "Sarah Kim",
      bio: "Growth engineer specializing in AI-powered sales automation.",
      role: "seller" as const,
      created_at: "2025-09-20",
    },
  },
  {
    id: "3",
    seller_id: "s3",
    title: "AI Data Analyst - Automated Reports & Insights",
    short_description: "Connects to your databases, generates insights, and creates beautiful reports automatically.",
    description: "This agent connects to PostgreSQL, MySQL, BigQuery, or Snowflake. It monitors your metrics, detects anomalies, generates weekly insight reports, and answers natural language questions about your data. No SQL knowledge needed.",
    category_id: "3",
    price: 599,
    price_type: "fixed" as const,
    tags: ["data-analysis", "reports", "sql", "bigquery"],
    images: [],
    status: "active" as const,
    rating: 4.9,
    review_count: 56,
    order_count: 180,
    created_at: "2025-11-20",
    seller: {
      id: "s3",
      email: "mike@example.com",
      name: "Mike Rodriguez",
      bio: "Data scientist turned AI agent builder. Making data accessible for everyone.",
      role: "seller" as const,
      created_at: "2025-08-15",
    },
  },
  {
    id: "4",
    seller_id: "s4",
    title: "SEO Content Writer Agent",
    short_description: "Writes SEO-optimized blog posts, landing pages, and product descriptions at scale.",
    description: "AI content creation agent that researches keywords, analyzes competitor content, and writes high-quality SEO articles. Outputs directly to WordPress, Ghost, or Webflow. Includes meta descriptions, internal linking suggestions, and readability scoring.",
    category_id: "4",
    price: 299,
    price_type: "fixed" as const,
    tags: ["content", "seo", "blog", "wordpress"],
    images: [],
    status: "active" as const,
    rating: 4.5,
    review_count: 203,
    order_count: 520,
    created_at: "2025-10-10",
    seller: {
      id: "s4",
      email: "emma@example.com",
      name: "Emma Patel",
      bio: "Content strategist building AI tools for marketers.",
      role: "seller" as const,
      created_at: "2025-07-01",
    },
  },
  {
    id: "5",
    seller_id: "s5",
    title: "Code Review & Bug Detection Agent",
    short_description: "Automated code review agent that catches bugs, security issues, and suggests improvements.",
    description: "This agent integrates with GitHub/GitLab and automatically reviews every PR. It catches bugs, security vulnerabilities, performance issues, and code style problems. Supports Python, JavaScript, TypeScript, Go, and Rust.",
    category_id: "5",
    price: 399,
    price_type: "fixed" as const,
    tags: ["code-review", "github", "security", "devtools"],
    images: [],
    status: "active" as const,
    rating: 4.7,
    review_count: 145,
    order_count: 290,
    created_at: "2025-12-05",
    seller: {
      id: "s5",
      email: "james@example.com",
      name: "James Wright",
      bio: "Senior SWE building developer tools powered by AI agents.",
      role: "seller" as const,
      created_at: "2025-10-15",
    },
  },
  {
    id: "6",
    seller_id: "s6",
    title: "Social Media Marketing Agent",
    short_description: "Plans, creates, and schedules social media content across all platforms.",
    description: "Full social media management agent. Creates content calendars, writes posts, generates images, schedules publishing across Instagram, Twitter/X, LinkedIn, and TikTok. Includes analytics and A/B testing of post formats.",
    category_id: "8",
    price: 349,
    price_type: "fixed" as const,
    tags: ["social-media", "marketing", "instagram", "linkedin"],
    images: [],
    status: "active" as const,
    rating: 4.4,
    review_count: 178,
    order_count: 410,
    created_at: "2025-11-01",
    seller: {
      id: "s6",
      email: "lisa@example.com",
      name: "Lisa Zhang",
      bio: "Digital marketer & AI enthusiast. Automating social media for 200+ brands.",
      role: "seller" as const,
      created_at: "2025-06-20",
    },
  },
];
